/**
 * Domain-layer error codes, thrown as `DomainException` subclasses.
 *
 * One member per domain invariant; every concrete error class in the domain
 * errors files (and the inline value-object errors) pins one of these. Kept in
 * the shared lib so the interface layer can render them without importing
 * domain internals.
 */
export enum DOMAIN_ERROR {
  // ── Clinic ────────────────────────────────────────────────────────────
  CLINIC_INVALID_NAME = 'DOMAIN_ERROR.CLINIC_INVALID_NAME',
  CLINIC_INVALID_USERNAME = 'DOMAIN_ERROR.CLINIC_INVALID_USERNAME',
  CLINIC_INVALID_USERNAME_FORMAT = 'DOMAIN_ERROR.CLINIC_INVALID_USERNAME_FORMAT',
  CLINIC_INVALID_PASSWORD_HASH = 'DOMAIN_ERROR.CLINIC_INVALID_PASSWORD_HASH',
  CLINIC_WEAK_PASSWORD = 'DOMAIN_ERROR.CLINIC_WEAK_PASSWORD',
  CLINIC_NOT_FOUND = 'DOMAIN_ERROR.CLINIC_NOT_FOUND',
  CLINIC_USERNAME_TAKEN = 'DOMAIN_ERROR.CLINIC_USERNAME_TAKEN',
  CLINIC_INVALID_CREDENTIALS = 'DOMAIN_ERROR.CLINIC_INVALID_CREDENTIALS',
  INVALID_CLINIC_ID = 'DOMAIN_ERROR.INVALID_CLINIC_ID',

  // ── Extraction schema ─────────────────────────────────────────────────
  SCHEMA_INVALID = 'DOMAIN_ERROR.SCHEMA_INVALID',
  SCHEMA_EMPTY = 'DOMAIN_ERROR.SCHEMA_EMPTY',
  SCHEMA_NOT_FOUND = 'DOMAIN_ERROR.SCHEMA_NOT_FOUND',
  SCHEMA_INVALID_ID = 'DOMAIN_ERROR.SCHEMA_INVALID_ID',
  SCHEMA_INVALID_FIELD_DEFINITION = 'DOMAIN_ERROR.SCHEMA_INVALID_FIELD_DEFINITION',

  // ── Referral ──────────────────────────────────────────────────────────
  REFERRAL_INVALID_ID = 'DOMAIN_ERROR.REFERRAL_INVALID_ID',
  REFERRAL_INVALID_PATIENT_NAME = 'DOMAIN_ERROR.REFERRAL_INVALID_PATIENT_NAME',
  REFERRAL_INVALID_FILE_NAME = 'DOMAIN_ERROR.REFERRAL_INVALID_FILE_NAME',
  REFERRAL_INVALID_STATUS = 'DOMAIN_ERROR.REFERRAL_INVALID_STATUS',
  REFERRAL_INVALID_STATUS_TRANSITION = 'DOMAIN_ERROR.REFERRAL_INVALID_STATUS_TRANSITION',
  REFERRAL_INVALID_BOUNDING_BOX = 'DOMAIN_ERROR.REFERRAL_INVALID_BOUNDING_BOX',
  REFERRAL_INVALID_EXTRACTED_FIELD = 'DOMAIN_ERROR.REFERRAL_INVALID_EXTRACTED_FIELD',
  REFERRAL_NOT_FOUND = 'DOMAIN_ERROR.REFERRAL_NOT_FOUND',
  REFERRAL_SCHEMA_ALREADY_FIXED = 'DOMAIN_ERROR.REFERRAL_SCHEMA_ALREADY_FIXED',
  REFERRAL_CORRECTION_NOT_ALLOWED = 'DOMAIN_ERROR.REFERRAL_CORRECTION_NOT_ALLOWED',
}

/**
 * Default HTTP status for each domain error code. Domain errors are business
 * facts and know their own "response worthiness" — mapping them centrally here
 * (rather than in a filter switch) keeps the interface layer dumb.
 */
export const DOMAIN_ERROR_STATUS: Record<DOMAIN_ERROR, number> = {
  [DOMAIN_ERROR.CLINIC_INVALID_NAME]: 400,
  [DOMAIN_ERROR.CLINIC_INVALID_USERNAME]: 400,
  [DOMAIN_ERROR.CLINIC_INVALID_USERNAME_FORMAT]: 400,
  [DOMAIN_ERROR.CLINIC_INVALID_PASSWORD_HASH]: 400,
  [DOMAIN_ERROR.CLINIC_WEAK_PASSWORD]: 400,
  [DOMAIN_ERROR.CLINIC_NOT_FOUND]: 404,
  [DOMAIN_ERROR.CLINIC_USERNAME_TAKEN]: 409,
  [DOMAIN_ERROR.CLINIC_INVALID_CREDENTIALS]: 401,
  [DOMAIN_ERROR.INVALID_CLINIC_ID]: 400,
  [DOMAIN_ERROR.SCHEMA_INVALID]: 400,
  [DOMAIN_ERROR.SCHEMA_EMPTY]: 400,
  [DOMAIN_ERROR.SCHEMA_NOT_FOUND]: 404,
  [DOMAIN_ERROR.SCHEMA_INVALID_ID]: 400,
  [DOMAIN_ERROR.SCHEMA_INVALID_FIELD_DEFINITION]: 400,
  [DOMAIN_ERROR.REFERRAL_INVALID_ID]: 400,
  [DOMAIN_ERROR.REFERRAL_INVALID_PATIENT_NAME]: 400,
  [DOMAIN_ERROR.REFERRAL_INVALID_FILE_NAME]: 400,
  [DOMAIN_ERROR.REFERRAL_INVALID_STATUS]: 400,
  [DOMAIN_ERROR.REFERRAL_INVALID_STATUS_TRANSITION]: 409,
  [DOMAIN_ERROR.REFERRAL_INVALID_BOUNDING_BOX]: 400,
  [DOMAIN_ERROR.REFERRAL_INVALID_EXTRACTED_FIELD]: 400,
  [DOMAIN_ERROR.REFERRAL_NOT_FOUND]: 404,
  [DOMAIN_ERROR.REFERRAL_SCHEMA_ALREADY_FIXED]: 409,
  [DOMAIN_ERROR.REFERRAL_CORRECTION_NOT_ALLOWED]: 409,
};
