/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new clinic account */
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate clinic and receive JWT bearer token */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinics/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated clinic profile */
        get: operations["ClinicsController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction-schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all extraction schema versions for authenticated clinic */
        get: operations["ClinicsController_listSchemas"];
        put?: never;
        /** Publish a new custom extraction schema version */
        post: operations["ClinicsController_createSchema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List paginated referrals for authenticated clinic */
        get: operations["ClinicsController_listReferrals"];
        put?: never;
        /** Create new referral and issue presigned S3 upload URL */
        post: operations["ClinicsController_createReferral"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get referral detail by ID with extracted payload and bounding boxes */
        get: operations["ClinicsController_getReferral"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct/Update extracted referral field values and bounding boxes */
        patch: operations["ClinicsController_updateReferral"];
        trace?: never;
    };
    "/referrals/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Real-time Server-Sent Events (SSE) status stream for processing referral */
        get: operations["ClinicsController_streamReferral"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignupRequest: {
            /** @description Full name or title of the clinic. */
            clinicName: string;
            /** @description Unique clinic username for authentication (3-50 chars, letters/numbers/_). */
            username: string;
            /** @description Account password (minimum 8 characters). */
            password: string;
        };
        ClinicDto: {
            /** @description Unique clinic ID (UUID). */
            id: string;
            /** @description Full name or title of the clinic. */
            clinicName: string;
            /** @description Unique clinic username. */
            username: string;
            /** @description Default extraction schema ID if configured. */
            defaultExtractionSchemaId: string | null;
            /**
             * Format: date-time
             * @description Account creation timestamp.
             */
            createdAt: string;
        };
        AuthResponseDto: {
            /** @description Sanitized clinic profile information. */
            clinic: components["schemas"]["ClinicDto"];
            /** @description Signed JWT authentication token. */
            token: string;
        };
        LoginRequest: {
            /** @description Clinic username for authentication. */
            username: string;
            /** @description Clinic account password. */
            password: string;
        };
        CreateExtractionSchemaRequest: {
            /**
             * @description Field definitions, accepted in either form:
             *      - an array of {@link SchemaFieldDefinitionDto} (in-app field builder), or
             *      - a flat `{ "field_name": "description" }` map (uploaded JSON config).
             *
             *     Both are normalised by `normalizeExtractionSchemaFields` before reaching
             *     the domain. Kept under this single property because the global
             *     `ValidationPipe` runs with `forbidNonWhitelisted: true` — a bare top-level
             *     map body would be rejected before it ever reached the controller.
             */
            fields: components["schemas"]["SchemaFieldDefinitionDto"][] | {
                [key: string]: string;
            };
        };
        SchemaFieldDefinitionDto: {
            /** @description Parameter name for the field, e.g. `policy_number`. */
            name?: string;
            /** @description Unique JSON property key for the extracted value. Defaults to `name`. */
            key?: string;
            /** @description Human-readable label displayed in UI workbench. Defaults to `name`. */
            label?: string;
            /** @description Mandatory guidance prompt description for Gemini LLM extractor. */
            description: string;
        };
        ExtractionSchemaDto: {
            /** @description Unique extraction schema ID (UUID). */
            id: string;
            /** @description Owning clinic ID (UUID). */
            clinicId: string;
            /** @description Schema version integer. */
            version: number;
            /** @description Array of field definitions in this schema. */
            fields: components["schemas"]["SchemaFieldDefinitionDto"][];
            /**
             * Format: date-time
             * @description Creation timestamp.
             */
            createdAt: string;
        };
        CreateReferralRequest: {
            /** @description Name of the patient associated with referral. */
            patientName: string;
            /** @description Optional target extraction schema ID override. */
            extractionSchemaId?: string | null;
        };
        BoundingBoxDto: {
            /** @description Normalized minimum X coordinate (0-1000). */
            xmin: number;
            /** @description Normalized minimum Y coordinate (0-1000). */
            ymin: number;
            /** @description Normalized maximum X coordinate (0-1000). */
            xmax: number;
            /** @description Normalized maximum Y coordinate (0-1000). */
            ymax: number;
        };
        ExtractedFieldDto: {
            /** @description Extracted text value. */
            value: string;
            /** @description 1-indexed page number in PDF document. */
            pageNumber: number;
            /** @description Spatial bounding box used to highlight the value on the PDF page. */
            boundingBox: components["schemas"]["BoundingBoxDto"] | null;
        };
        UpdateReferralRequest: {
            /** @description Updated payload of extracted fields corrected by staff user. */
            extractedPayload: components["schemas"]["ExtractedFieldDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Clinic registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Invalid input or password requirements not met */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Username is already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
            /** @description Invalid username or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicsController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clinic profile details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicsController_listSchemas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of extraction schema versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionSchemaDto"][];
                };
            };
        };
    };
    ClinicsController_createSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExtractionSchemaRequest"];
            };
        };
        responses: {
            /** @description Extraction schema published */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionSchemaDto"];
                };
            };
        };
    };
    ClinicsController_listReferrals: {
        parameters: {
            query?: {
                /** @description Page number for pagination (starts at 1). */
                page?: number;
                /** @description Page size limit (maximum 100). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of referrals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicsController_createReferral: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReferralRequest"];
            };
        };
        responses: {
            /** @description Referral created and presigned S3 URL issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicsController_getReferral: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Referral detail record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Referral not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicsController_updateReferral: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReferralRequest"];
            };
        };
        responses: {
            /** @description Referral record updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicsController_streamReferral: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE event stream connection established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
